name: Kernel Multi-Arch CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-i386:
    name: Build i386
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            nasm \
            gcc \
            gcc-multilib \
            binutils \
            grub-pc-bin \
            grub-common \
            xorriso \
            mtools

      - name: Compilar i386
        run: make all

      - name: Guardar Artefato i386
        uses: actions/upload-artifact@v4
        with:
          name: kernel-i386
          path: |
            *.iso
            vmicaro.iso

  build-xtensa:
    name: Build Xtensa
    runs-on: ubuntu-latest
    container: espressif/idf:v5.1

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4

      - name: Compilar Xtensa
        run: |
          . $IDF_PATH/export.sh
          make -C arch/Xtensa

      - name: Guardar Artefato Xtensa
        uses: actions/upload-artifact@v4
        with:
          name: kernel-xtensa
          path: |
            arch/Xtensa/*.elf
            arch/Xtensa/*.bin

